Add some new check: dpkg check kpm check OS Check root check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2,7 +2,6 @@
 # This file is not generated by autoconf
 # Please do not try to modify this file
 
-# Checking Current Shell
 CONF_SHELL_BASH(){
 	echo -n 'Checking current Shell ... '
 	SH=$(echo $SHELL|sed -rne 's@.*/@@p')
@@ -329,8 +328,94 @@ CONF_LIBGCC64(){
 	fi
 }
 
+CONF_ROOT(){
+	echo -n "Checking current user is root ... "
+	U=$(whoami)
+	if [ "$U" = "root" ];then
+		echo yes
+		if [ $FORCE_UNSAFE_CONFIGURE ] && [ $FORCE_UNSAFE_CONFIGURE -eq 1 ];then
+			return 0
+		else
+			echo "Root User is not recommended, if you want to do so"
+			echo "Please run following command and retry:"
+			echo "export FORCE_UNSAFE_CONFIGURE=1"
+			exit 1
+		fi
+	else
+		echo no
+		return 0
+	fi
+}
+
+CONF_DEBIAN(){
+	DEBIAN=0
+	UBUNTU=0
+	KALI=0
+	KS=0
+	DEEPIN=0
+	
+	echo -n "Checking OS Type ... "
+	OSTYPE=$(cat /etc/issue|sed -rne "s/ .*//p")
+	echo $OSTYPE
+	case $OSTYPE in
+		Ubuntu)
+			UBUNTU=1
+			;;
+		Debian)
+			DEBIAN=1
+			;;
+		Kali)
+			KALI=1
+			;;
+		Deepin)
+			DEEPIN=1
+			;;
+		KSLinux|Kurosawa)
+			KS=1
+			;;
+		*)			
+			if [ $FORCE_NO_DEB_KPM_SYSTEM ] && [ $FORCE_NO_DEB_KPM_SYSTEM -eq 1 ];then
+				return 0
+			else
+				echo "KSLinux can only build on deb-based systems or"
+				echo "kpm-based systems,you can run following command"
+				echo "to skip this check:"
+				echo "export FORCE_NO_DEB_KPM_SYSTEM=1"
+				exit 1
+			fi
+			;;			
+	esac
+	return 0
+}
+
+CONF_KPM(){
+	echo -n 'Checking Package Manager ... '
+	KPM="/usr/bin/kpm"
+	DPKG="/usr/bin/dpkg"
+	if [ -f $KPM ];then
+		echo $KPM
+		return 0
+	elif [ -f $DPKG ];then
+		echo $DPKG
+		return 0
+	else
+		echo "not found"
+		if [ $NO_PACKAGE_MANAGER ] && [ $NO_PACKAGE_MANAGER -eq 1 ];then
+				return 0
+		else
+			echo "Please install Package Manager (dpkg) or (kpm) manually"
+			echo "or run following command to skip this check:"
+			echo "export NO_PACKAGE_MANAGER=1"
+			exit 1
+		fi
+	fi
+}
+
+CONF_DEBIAN
+CONF_ROOT
 CONF_SHELL_BASH
 CONF_SH_BASH
+CONF_KPM
 CONF_YACC
 CONF_YACC_BISON
 CONF_AWK
@@ -345,6 +430,6 @@ CONF_GCC
 CONF_GXX
 CONF_LIBGCC
 CONF_LIBGCC64
-CONF_LOG
+#CONF_LOG
 
 
